[package]
name = "u2f"
version = "0.1.0"
authors = ["Daniel Basedow <daniel.basedow@gmail.com>"]
edition = "2018"

[dependencies]
base64 = "0.10"
ring = "0.14"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
untrusted = "0.6"
webpki = "0.19"
